name: nice_image
description: Beautiful random image generator
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  cached_network_image: ^3.3.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.7
  injectable: ^2.3.2
  intl: ^0.20.2
  palette_generator: ^0.3.3+3

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
